// Code generated by protoc-gen-go.
// source: balancestorage.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	balancestorage.proto

It has these top-level messages:
	GetRequest
	BalanceResponse
	BalanceRecord
	AllResponse
	IncrementRequest
	SetRequest
	AllRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type GetRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BalanceResponse struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *BalanceResponse) Reset()                    { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string            { return proto1.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()               {}
func (*BalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BalanceRecord struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Value  int64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *BalanceRecord) Reset()                    { *m = BalanceRecord{} }
func (m *BalanceRecord) String() string            { return proto1.CompactTextString(m) }
func (*BalanceRecord) ProtoMessage()               {}
func (*BalanceRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AllResponse struct {
	Records []*BalanceRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *AllResponse) Reset()                    { *m = AllResponse{} }
func (m *AllResponse) String() string            { return proto1.CompactTextString(m) }
func (*AllResponse) ProtoMessage()               {}
func (*AllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AllResponse) GetRecords() []*BalanceRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type IncrementRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Amount int64 `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *IncrementRequest) Reset()                    { *m = IncrementRequest{} }
func (m *IncrementRequest) String() string            { return proto1.CompactTextString(m) }
func (*IncrementRequest) ProtoMessage()               {}
func (*IncrementRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SetRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Value  int64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AllRequest struct {
}

func (m *AllRequest) Reset()                    { *m = AllRequest{} }
func (m *AllRequest) String() string            { return proto1.CompactTextString(m) }
func (*AllRequest) ProtoMessage()               {}
func (*AllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto1.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto1.RegisterType((*BalanceResponse)(nil), "proto.BalanceResponse")
	proto1.RegisterType((*BalanceRecord)(nil), "proto.BalanceRecord")
	proto1.RegisterType((*AllResponse)(nil), "proto.AllResponse")
	proto1.RegisterType((*IncrementRequest)(nil), "proto.IncrementRequest")
	proto1.RegisterType((*SetRequest)(nil), "proto.SetRequest")
	proto1.RegisterType((*AllRequest)(nil), "proto.AllRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for BalanceStorage service

type BalanceStorageClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllResponse, error)
}

type balanceStorageClient struct {
	cc *grpc.ClientConn
}

func NewBalanceStorageClient(cc *grpc.ClientConn) BalanceStorageClient {
	return &balanceStorageClient{cc}
}

func (c *balanceStorageClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := grpc.Invoke(ctx, "/proto.BalanceStorage/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceStorageClient) Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := grpc.Invoke(ctx, "/proto.BalanceStorage/Increment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceStorageClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := grpc.Invoke(ctx, "/proto.BalanceStorage/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceStorageClient) All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllResponse, error) {
	out := new(AllResponse)
	err := grpc.Invoke(ctx, "/proto.BalanceStorage/All", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BalanceStorage service

type BalanceStorageServer interface {
	Get(context.Context, *GetRequest) (*BalanceResponse, error)
	Increment(context.Context, *IncrementRequest) (*BalanceResponse, error)
	Set(context.Context, *SetRequest) (*BalanceResponse, error)
	All(context.Context, *AllRequest) (*AllResponse, error)
}

func RegisterBalanceStorageServer(s *grpc.Server, srv BalanceStorageServer) {
	s.RegisterService(&_BalanceStorage_serviceDesc, srv)
}

func _BalanceStorage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BalanceStorageServer).Get(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BalanceStorage_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(IncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BalanceStorageServer).Increment(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BalanceStorage_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BalanceStorageServer).Set(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BalanceStorage_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BalanceStorageServer).All(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BalanceStorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BalanceStorage",
	HandlerType: (*BalanceStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _BalanceStorage_Get_Handler,
		},
		{
			MethodName: "Increment",
			Handler:    _BalanceStorage_Increment_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _BalanceStorage_Set_Handler,
		},
		{
			MethodName: "All",
			Handler:    _BalanceStorage_All_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xa9, 0x65, 0x1b, 0x9e, 0xb9, 0x4d, 0x2f, 0x43, 0x65, 0x20, 0x8c, 0x82, 0xb0, 0x87,
	0x31, 0x65, 0xf3, 0xd1, 0x17, 0x7d, 0x11, 0x5f, 0xd7, 0x1f, 0x20, 0x59, 0x77, 0x11, 0xa1, 0x4b,
	0x66, 0xd2, 0xfa, 0x7b, 0xfd, 0x29, 0x86, 0x34, 0xa4, 0xb5, 0x52, 0x7c, 0x0a, 0xdc, 0x9c, 0x73,
	0xcf, 0x77, 0x2e, 0xa6, 0x3b, 0x91, 0x0b, 0x99, 0xb1, 0x29, 0x94, 0x16, 0xef, 0xbc, 0x3a, 0x6a,
	0x55, 0x28, 0xea, 0xb9, 0x27, 0xb9, 0x01, 0x5e, 0xb8, 0xd8, 0xf2, 0x67, 0x69, 0xff, 0x69, 0x82,
	0x41, 0x69, 0x58, 0xbf, 0x7d, 0xec, 0xaf, 0xa3, 0x79, 0xb4, 0x88, 0x93, 0x39, 0x26, 0xcf, 0x95,
	0x7b, 0xcb, 0xe6, 0xa8, 0xa4, 0x61, 0x1a, 0xa1, 0xf7, 0x25, 0xf2, 0x92, 0xbd, 0xe2, 0x0e, 0xa3,
	0xa0, 0xc8, 0x94, 0xde, 0xff, 0xd9, 0x51, 0x1b, 0x4e, 0x9c, 0xe1, 0x01, 0xc3, 0xa7, 0x3c, 0x0f,
	0xeb, 0x6e, 0x31, 0xd0, 0xce, 0x68, 0xac, 0x3c, 0x5e, 0x0c, 0xd7, 0xd3, 0x0a, 0x70, 0xf5, 0x6b,
	0x6b, 0xb2, 0xc1, 0xf9, 0xab, 0xcc, 0x34, 0x1f, 0x58, 0x76, 0xd2, 0xd2, 0x18, 0x7d, 0x71, 0x50,
	0xa5, 0x2c, 0x7c, 0xd4, 0x12, 0x48, 0xbb, 0xcb, 0xb5, 0xc1, 0xce, 0x00, 0x07, 0xe6, 0xd4, 0xeb,
	0xef, 0x08, 0x63, 0x8f, 0x90, 0x56, 0x87, 0xa3, 0x7b, 0xc4, 0xf6, 0x56, 0x74, 0xe1, 0x01, 0xeb,
	0xbb, 0xcd, 0x2e, 0xdb, 0xcc, 0xbe, 0xdc, 0x23, 0x4e, 0x03, 0x35, 0x5d, 0x79, 0x51, 0xbb, 0x47,
	0xa7, 0xdb, 0xe6, 0xa5, 0x8d, 0xbc, 0xf4, 0xff, 0xbc, 0x25, 0x62, 0x5b, 0x21, 0x38, 0xea, 0x3a,
	0x33, 0x6a, 0x8e, 0x2a, 0xf5, 0xae, 0xef, 0x46, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x3a, 0x66, 0xeb, 0x21, 0x02, 0x00, 0x00,
}
